### ISSUE TITLE
Open discussion on Tag Locking

### ISSUE THREAD

**Issue by SteveLasker** [AzureCR/specs#2]
Speclet: https://github.com/AzureCR/specs/tree/master/tag_locking

**Comment by tgarlot** [comment]
Not sure if it's part of this feature: would be nice also prevent a tag to be "re-used". 
Example: my CI job create an image with tag "Build123". It should not be possible to push an image with the same Tag twice (more to prevent manual error)

**Comment by SteveLasker** [comment]
@tgarlot yup, that's exactly what the policy does. By enabling tag locking, pushing an update to an existing tag will fail. Part of the policy will support excluding tags you want updated, such as the dreaded :latest. Or, perhaps you have stable tags you want to update. See [Tagging Best Practices](https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/)

**Comment by SteveLasker** [comment]
quick click, didn't mean to close...

**Comment by justin-vanwinkle** [comment]
Love this idea!  An organization I am currently working with does builds for dev on the next incremental tag (0.0.x) until they are ready to lock in that version.  When they lock in a version, that tag would ideally be able to be locked and all new dev builds would move to update 0.0.x+1.

So being able to update 0.0.x until it is locked would be valuable to them.  Is that what you are proposing (a tag-based lock), or are you saying it should be a global lock for a registry?

**Comment by SteveLasker** [comment]
Thanks Justin,
The post is to solicit feedback. We were thinking both repo and registry global, per the customers requirements. 
I would encourage unique tagging for all deployed builds as a best practice, but we realize there are lots of scenarios. https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by justin-vanwinkle** [comment]
Thanks for that article!
I don't believe that it is a "best" practice.  It certainly is a good practice for some scenarios.  Even MSFT does not follow the unique tagging practice: https://hub.docker.com/r/microsoft/windowsservercore/tags/
So locking on a per-tag basis might also make more sense for the teams that maintain those images -- and for non-MSFT teams that do similar practices.  Thoughts?

**Comment by SteveLasker** [comment]
Hi Justin,
The Windows Server images use base image tagging, as most customers use them as the base in their dockerfile, not the deployed images. So, unique are the images you deploy to an environment, stable used for images you'd want to update. 
I should also add, there's an evolving pattern for using channels to provide a more robust stable and unique tagging solution to support updates. So, we hope to see this evolve as well. 
Steve

**Comment by SteveLasker** [comment]
Tag locking is now complete. Thanks for the feedback. https://aka.ms/acr/tag-locking
We'll have more granular capabilities with the per-repo permissions coming soon.
