### ISSUE TITLE
mcr and tag listing via a http api

### ISSUE THREAD

**Issue by Koubek** [AzureCR/specs#3]
Hi, I don't really know whether this repo is the best one to place my question but I don't know where else to do it. So sorry if I am breaking some rules, really.

I would like to know the following: Does mcr.microsoft.com support some HTTP API? I am right now particularly interested in the listing of the tags for a specific image.

The new images were migrated from Docker Hub where the listing worked (some private images were also one specific time directly on ACR available to some MS partners and the listing was also working, just the interface was a little bit different if I can remember well).

Now, mcr.microsoft.com doesn't support the listings or I can't find the correct way. But I was also told by a MS guy maintaining the repo that mcr currently doesn't support the listings. 

So I would like to know what is the plan etc.

Thank you very much for any information.

**Comment by Koubek** [comment]
Hi @SteveLasker 
I think I have found the API but the operation seems to be blocked:

https://mcr.microsoft.com/v2/businesscentral/onprem/tags/list
or
https://mcr.microsoft.com/v2/repositories/businesscentral/onprem/tags/list

![image](https://user-images.githubusercontent.com/24265973/46849477-b4984500-ce00-11e8-9a0a-bcc2de16bc8c.png)

**Comment by SteveLasker** [comment]
Hi @Koubek yeah, we've had a bunch of requests around this lately. mcr doesn't currently support a repo listing, or tag listing. Our goal is it integrate with Docker Hub. That said, the request for tooling scenarios is something we've added to our backlog. WIth mcr being a public/anonymous registry at massive scale, we just need to finish the hardening on that particular api. So, yes, it will be coming, but we don't yet have a date. 
Steve

**Comment by Koubek** [comment]
Hi @SteveLasker, any estimation? I really appreciate MS movement toward containers, this is really amazing. I can also understand you decided to host images in your own repositories. But please, don't break good things that have been working for us for a long time. This is really annoying as we need to figure out now how to overcome missing functionality so also we need to break our products. I hope you understand that this is far from the optimum approach for MS partners (and also for many of our customers).

**Comment by SteveLasker** [comment]
Hi @Koubek,
This was just a blind spot we missed. We knew we didn't know everything customers were using, so we've intentionally taken a staggered approach to moving images over from microsoft/*
We considered Q1-2018, but we've had enough feedback that we've pulled the list api in. We're currently scheduled for getting this done in December. Apologies for the gap. We're also getting a repo up for tracking MCR issues.
Thanks,
Steve

**Comment by Koubek** [comment]
Hi @SteveLasker, thank you very much for your response. 
Please, close the issue once the API is public.
Thanks again.

**Comment by Koubek** [comment]
Hi @SteveLasker, I think we can close the issue now.
